version: '3.8'

services:
  # Serviço do MySQL
  mysql:
    image: mysql:8.0                         # Usa a imagem oficial do MySQL 8.0
    container_name: mysql_container           # Nome do container MySQL
    environment:                              # Configurações do banco de dados
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pessoa_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"                           # Porta local → Container
    networks:
      - spring_network                        # Rede para comunicação

  # Serviço do Spring Boot
  spring_app:
    build: .                                  # Constrói o projeto Spring Boot
    container_name: spring_pessoa             # Nome do container Spring Boot
    ports:
      - "8080:8080"                           # Porta do Spring Boot
    environment:                              # Variáveis de ambiente
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pessoa_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql                                 # Espera o MySQL iniciar
    networks:
      - spring_network

# Define a rede interna do Docker
networks:
  spring_network:

